### ISSUE TITLE
非常棒的工作

### ISSUE THREAD

**Issue by ocrhei** [retsuh-bqw/SRFormer-Text-Det#1]
作者您好，请问您能提供一下不预训练情况下的totaltext或者ctw1500的配置文件吗，因为我想类似yolo+dptext-detr那篇工作一样进行魔改，但如果先预训练的话，时间太久了，没有那么多卡跑，呜呜呜。
万分感谢。

**Comment by retsuh-bqw** [comment]
1. Detectron2 加载权重过程中对自动丢弃key不符合或权重维度不符合的部分，您可以将配置文件中MODEL.WEIGHTS参数改为我们提供的预训练权重路径或者改为预训练配置文件中的"detectron2://ImageNetPretrained/torchvision/R-50.pkl"来加载官方提供的imagenet-pretrain backbone权重
2. 可以适当提高learning rate来符合‘train from scratch’的需求
3. 影响模型结构的配置全部在Base.yaml中，绝大部分为Detectron2默认提供，也可以自己在./adet/config/defaults.py文件中注册
4. 从另一个角度讲，我们用于预训练的配置文件即是在没有预训练情况下的训练，只需改数据集相关配置即可，相关配置参数可以参考./adet/data/builtin.py文件中’_PREDEFINED_SPLITS_TEXT‘变量或者针对其他数据集提供的配置文件。

**Comment by 921162820** [comment]
> 1. Detectron2 加载权重过程中对自动丢弃key不符合或权重维度不符合的部分，您可以将配置文件中MODEL.WEIGHTS参数改为我们提供的预训练权重路径或者改为预训练配置文件中的"detectron2://ImageNetPretrained/torchvision/R-50.pkl"来加载官方提供的imagenet-pretrain backbone权重
> 2. 可以适当提高learning rate来符合‘train from scratch’的需求
> 3. 影响模型结构的配置全部在Base.yaml中，绝大部分为Detectron2默认提供，也可以自己在./adet/config/defaults.py文件中注册
> 4. 从另一个角度讲，我们用于预训练的配置文件即是在没有预训练情况下的训练，只需改数据集相关配置即可，相关配置参数可以参考./adet/data/builtin.py文件中’_PREDEFINED_SPLITS_TEXT‘变量或者针对其他数据集提供的配置文件。

感谢指点，我试试
