### ISSUE TITLE
How to get the tight bounding box around polygon? 

### ISSUE THREAD

**Issue by lee-hyun-a** [retsuh-bqw/SRFormer-Text-Det#15]
Hi, thanks for your research.

I want to get the bounding box in the prediction of model.
How can I get the bounding box coordinates in a prediction instance of SRFormer?
Do I need to leverage polygon coordinates?

**Comment by retsuh-bqw** [comment]
Thanks for your interest in our work.

The easiest way of getting the bounding box coordinates is to post-process the polygon output. I think you can try with `cv2.boundingRect` function.
