### ISSUE TITLE
Data in 'Data Preparation' is different with real code.

### ISSUE THREAD

**Issue by Fulitcher** [retsuh-bqw/SRFormer-Text-Det#18]
"Total-Text" in your Onedrive doesnt have below labels...
  |  |- test_poly.json
   |  |─ train_poly_pos.json
   |  └─ train_poly_rotate_pos.json
It has only two folder which is "test_images_rotate", "train_images_rotate"

"CTW1500" in your Onedrive doesnt have...
   |  |- test_images
   |  |- train_images_rotate
   |  |- test_poly.json
   |  └─ train_poly_rotate_pos.json
But It has only
   |  |- annotations
   |  └─ test_ctw1500_maxlen100.json
   |  └─train_ctw1500_maxlen100_v2.json
   |  |- ctwtest_text_image
   |  |- ctwtrain_text_image

But other datasets also have different structure(MLT, and so on)

Do I need some more pre-process for your ideal data structure on README??

**Comment by retsuh-bqw** [comment]
Annotations of `json` formats are provided in another separated file: [OneDrive](https://1drv.ms/u/s!AtF4kB5K12hqgVr0wHEUD7XzVePw?e=EKcBDC)

**Comment by Fulitcher** [comment]
@retsuh-bqw Thank you!!
