### ISSUE TITLE
in installing issue 

### ISSUE THREAD

**Issue by 1301krishmittal** [retsuh-bqw/SRFormer-Text-Det#3]
Building wheels for collected packages: Polygon3
  Building wheel for Polygon3 (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      NumPy extension not found - disabling support for it!
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\Polygon
      copying Polygon\IO.py -> build\lib.win-amd64-cpython-310\Polygon
      copying Polygon\Shapes.py -> build\lib.win-amd64-cpython-310\Polygon
      copying Polygon\Utils.py -> build\lib.win-amd64-cpython-310\Polygon
      copying Polygon\__init__.py -> build\lib.win-amd64-cpython-310\Polygon
      running build_ext
      building 'Polygon.cPolygon' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Polygon3
  Running setup.py clean for Polygon3
Failed to build Polygon3
ERROR: Could not build wheels for Polygon3, which is required to install pyproject.toml-based projects

**Comment by 1301krishmittal** [comment]
this is issue while installing and dont know how to resolve it

**Comment by retsuh-bqw** [comment]
As mentioned in the error, perhaps you need a higher version of the Microsoft Visual C++. As all my experiments are conducted on servers with linux system, I'm sorry I can't be of further assistance.

**Comment by tm1412** [comment]
When I use this command: "pip install torch==1.13.1+cu111 torchvision==0.10.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html", it reports that it cannot find the torch and torchvision versions as specified in the command. Is it possible for me to switch to different versions?
