### ISSUE TITLE
Preprocess my own data?

### ISSUE THREAD

**Issue by tm1412** [retsuh-bqw/SRFormer-Text-Det#4]
How can I preprocess my own data, and what does a dataset require?

**Comment by retsuh-bqw** [comment]
As our method is built upon Detectron2, you can refer to this doc (https://detectron2.readthedocs.io/tutorials/datasets.html) to train/evaluate with your own datasets.

Basically, what you need to do is:
1. Convert your own annotation to COCO format
2. Register your dataset in [this line](https://github.com/retsuh-bqw/SRFormer-Text-Det/blob/71e15b1d360a576d7316c41f754a4fb8315dec0a/adet/data/builtin.py#L19C7-L19C7) following existing format (i.e., _dataset_name: (path_to_images, path_to_json_annotations_)
3. That's pretty much all you need to do for evaluation. If you want to train models on your own data, plz leverage [this script](https://github.com/ymy-k/DPText-DETR/blob/c62baaed9da69b58280b2756720eb37c19a91058/process_positional_label.py#L189C5-L189C42)(provided by DPText-DETR) to convert your annotation file to desired formulations (where each point of the polygon is arranged in clockwise order and the starting point is determined by reading direction)

The dataset only requires images and polygon annotations. Our gt for segmentation masks is also derived from shrunken polygon areas.
