### ISSUE TITLE
installing pytorch still giving module not found 

### ISSUE THREAD

**Issue by krishmittal1301** [retsuh-bqw/SRFormer-Text-Det#5]
i installed pytorch still it shows no installation why 
![Screenshot from 2023-10-25 16-01-24](https://github.com/retsuh-bqw/SRFormer-Text-Det/assets/148966133/2437dbb2-5b65-4861-ad22-9e5eb03bae67)

**Comment by krishmittal1301** [comment]
why its happening i am not able to understand

**Comment by retsuh-bqw** [comment]
It could be due to environment variables setting (e.g. $PATH). 
A simple way to solve this is to use: `python -m pip install <package>` 
instead of just: `pip install <package>`
