### ISSUE TITLE
Issue when run setup

### ISSUE THREAD

**Issue by tm1412** [retsuh-bqw/SRFormer-Text-Det#6]
![image](https://github.com/retsuh-bqw/SRFormer-Text-Det/assets/135865345/daea740e-ee89-4571-81c0-e6675d15d8c5)

![395540034_350825724006085_7012748587980626180_n](https://github.com/retsuh-bqw/SRFormer-Text-Det/assets/135865345/cc840bd8-b023-4319-ae66-0a55a381cd43)

I have tried running the setup file on both my personal computer and Google Colab, but both received error messages. Can you help me fix this?

**Comment by rmast** [comment]
It appears your torch install doesn't fit your cuda install. Look for the exact requirements of installing torch.
