### ISSUE TITLE
How did you prepare valid_mlt datasets?

### ISSUE THREAD

**Issue by Swall0w** [retsuh-bqw/SRFormer-Text-Det#7]
@retsuh-bqw Thank you for your excellent work.
I have one training question.
In the readme, there is a data set composition, how was the data for the valid_mlt images prepared?
I understood the *.json file, but did not know where to download the images from.

I also checked this page, but it was not divided into Arabic, Bangla, etc.
https://rrc.cvc.uab.es/?ch=8&com=downloads

```bash
   |- valid_mlt
   |  |- All
   |  |- Arabic
   |  |- Bangla
   |  |- Chinese
   |  |- Japanese
   |  |- Korean
   |  |- Latin
   |  |- Arabic_test.json
   |  |- Bangla_test.json
   |  |- Chinese_test_json
   |  |- Japanese_test.json
   |  |- Korean_test.json
   |  |- Latin_test.json
   |  └─ mlt_valid_test.json
```

**Comment by retsuh-bqw** [comment]
It was an oversight on my part,. Actually, the validation slips of MLT-17 is downloaded from the official [Robust Reading Competition website](https://rrc.cvc.uab.es/?ch=8&com=downloads). 
![截屏2023-11-21 13 34 02](https://github.com/retsuh-bqw/SRFormer-Text-Det/assets/64821056/d7da5dc0-9b16-40d0-84ea-17abedf91f37)
I've divided these images into the six major languages shown here, based on the primary language (has the largest number of words) in each image. I'll soon update the RADEME with a download link to my processed images along with their annotations.

**Comment by Swall0w** [comment]
@retsuh-bqw Thank you very much. Understood.
I appreciate it very much.

**Comment by retsuh-bqw** [comment]
@Swall0w The processed dataset is now available at [OneDrive](https://1drv.ms/u/s!AtF4kB5K12hqgXCzVB5JUNSW3wRP?e=IrydBa).
