### ISSUE TITLE
precision、recall、hmean的结果都是0？

### ISSUE THREAD

**Issue by Cookie477** [retsuh-bqw/SRFormer-Text-Det#8]
作者您好，我用您预训练的模型评估ctw1500数据集，请问为什么precision、recall、hmean的结果都是0？

**Comment by retsuh-bqw** [comment]
> 作者您好，我用您预训练的模型评估ctw1500数据集，请问为什么precision、recall、hmean的结果都是0？

The pre-trained weights we provided is one of model variant with only 2 Segmentation&Regression Chunks.
https://github.com/retsuh-bqw/SRFormer-Text-Det/blob/c71354939e576353f5ae202f2ca559ad3fd255e6/configs/SRFormer/Base.yaml#L26C8-L26C8

**Comment by Cookie477** [comment]
作者您好，按您的要求更改配置后，仍然出现这个问题；之前也用微调模型进行评估过，也是同样的问题。
检查运行过程，发现出现以下问题。麻烦作者帮忙看一下，是不是因为这个原因，该如何解决？还是其他版本问题？万分感谢！
![image](https://github.com/retsuh-bqw/SRFormer-Text-Det/assets/153697366/9d0fa83d-0b1c-4d89-b36e-09bc58b8ad41)
结果：
<img width="725" alt="2" src="https://github.com/retsuh-bqw/SRFormer-Text-Det/assets/153697366/162c4bac-f16d-445d-98c0-0f7738166251">

**Comment by retsuh-bqw** [comment]
I retested the uploaded models and they all worked correctly and reproduced the results：
<img width="1200" alt="截屏2023-12-15 00 35 06" src="https://github.com/retsuh-bqw/SRFormer-Text-Det/assets/64821056/aae0c6b5-3c88-44f3-8316-f9612929645d">
The warning info you noted may not be a problem. Are you using the dataset we provided?

**Comment by Cocty** [comment]
@retsuh-bqw 作者你好，我按照你的要求把那个配置文件的seg_layers改成2之后在ctw1500数据集上得到的结果如下：
![image](https://github.com/user-attachments/assets/6dce9604-d217-4930-bfe9-3985c871b19d)
请问这个是什么原因导致的呢

**Comment by Cocty** [comment]
跟原文的结果相差比较大 @retsuh-bqw ，十分期待您的回复

**Comment by retsuh-bqw** [comment]
> 跟原文的结果相差比较大 @retsuh-bqw ，十分期待您的回复

Which checkpoint are you using?

**Comment by Cocty** [comment]
> > 跟原文的结果相差比较大 @retsuh-bqw ，十分期待您的回复
> 
> Which checkpoint are you using?
![image](https://github.com/user-attachments/assets/fb2c9032-e53f-49f9-ab48-84362c00d8ec)
我预训练模型使用的是您的pretrain_model，然后outputdir使用的是那个tune，以上是我的配置文件，请问我微调的时候是需要指定哪个模型呢？

**Comment by Cocty** [comment]
请问这个https://github.com/retsuh-bqw/SRFormer-Text-Det/issues/8#issuecomment-2482134236里面的model.weights是需要指定您给的哪个微调模型呢？

**Comment by retsuh-bqw** [comment]
> 我预训练模型使用的是您的pretrain_model，然后outputdir使用的是那个tune，以上是我的配置文件，请问我微调的时候是需要指定哪个模型呢？

It's OK to finetune our pretrained model provided. But I've noticed that you are using a batch size of 1, which will inevitably lead to unstable training. Please use larger batch sizes instead.
